# Generated by Django 4.2.2 on 2023-06-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoPlot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoPlot',
        ),
    ]
