# Generated by Django 4.2.2 on 2023-06-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoPlot', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoPlot',
            new_name='AutoPlot_model',
        ),
    ]
